### ISSUE TITLE
Facing this issue when syncing -> panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by jacquesvcritien** [okx/xlayer-erigon#8]
#### System information

OS & Version: Linux

Commit hash: bd77b53e4e3e0c774a70fb76e33442b83bad75c2

Chain/Network: testnet

#### Expected behaviour

Syncs normally

#### Actual behaviour

Service crashes and restarts, resulting in the same error

#### Steps to reproduce the behaviour

Just starting the node normally
```
/home/node/xlayer-erigon/build/bin/cdk-erigon --config="/home/node/xlayer-erigon/xlayerconfig-testnet.yaml"
```
#### Backtrace

````
Apr 30 04:04:49 cdk-erigon[336859]: [INFO] [04-30|04:04:49.544] [4/15 Senders] Started                   from=627449 to=627528
Apr 30 04:04:49 cdk-erigon[336859]: [INFO] [04-30|04:04:49.551] [4/15 Senders] Finished
Apr 30 04:04:49 cdk-erigon[336859]: [INFO] [04-30|04:04:49.681] [5/15 Execution] Short circuit           batch=27050 block=627528
Apr 30 04:04:49 cdk-erigon[336859]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 30 04:04:49 cdk-erigon[336859]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x54 pc=0x13f14dc]
Apr 30 04:04:49 cdk-erigon[336859]: goroutine 154 [running]:
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/eth/stagedsync.SpawnExecuteBlocksStageZk(_, {_, _}, {_, _}, _, {_, _}, {{0x2eecf50, 0xc0001d20e0}, ...}, ...)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/eth/stagedsync/stage_execute_zkevm.go:132 +0x97c
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func13(0x80?, 0x1b?, 0x26024d4?, {0x2eafb60?, 0xc0008f1b80?}, {0x0?, 0x0?}, 0xe0?)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/zk/stages/stages.go:334 +0x9b
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0008f1b80, 0xc000736fa0, {0x2eecf50?, 0xc0001d20e0}, {0x0?, 0x0}, 0x40?, 0x97?, 0xfa?)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0008f1b80, {0x2eecf50, 0xc0001d20e0}, {0x0, 0x0}, 0xe5?, 0x81?)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2ed2d30?, 0xc000fc4400}, 0xc0043b5e10?, {0x2eecf50, 0xc0001d20e0}, 0xc0008f1b80, 0xc0005a15a0, 0x1, 0xc000650960)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
Apr 30 04:04:49 cdk-erigon[336859]: github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2ed2d30, 0xc000fc4400}, 0x1?, {0x2eecf50?, 0xc0001d20e0}, 0x0?, 0xc0001bc900, 0xc0043c3b00?, 0xc0043b5fb8?, 0xc0013ce0c0, ...)
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
Apr 30 04:04:49 cdk-erigon[336859]: created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
Apr 30 04:04:49 cdk-erigon[336859]:         github.com/ledgerwatch/erigon/eth/backend.go:1337 +0x213
````

**Comment by zjg555543** [comment]
Thanks your feedback.BTW what's your config detail?
